FROM python:3.9-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY ../../requirements.txt /app/requirements.txt
COPY ../el_delivery /app/el_delivery
COPY ../el_orders /app/el_orders
COPY start.sh /app/start.sh

RUN pip install --no-cache-dir -r /app/requirements.txt 

RUN apt-get update && apt-get install -y cron && rm -rf /var/lib/apt/lists/* \
    && chmod +x /app/start.sh

RUN echo "*/2 * * * * root KAFKA_IP=\$KAFKA_IP /bin/bash /app/start.sh >> /var/log/cron.log 2>&1" > /etc/cron.d/cron_job

RUN chmod 0644 /etc/cron.d/cron_job && touch /var/log/cron.log

CMD ["bash", "-c", "cron && tail -f /var/log/cron.log"]
